routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('menu1', function(){
	return view('menu1.index');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('empleados','EmpleadoController');
Route::resource('puestos','PuestoController');
Route::resource('asistencias','AsistenciaController');

app/Empleado.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
    protected $fillable = ['codigo','nombre','apellido','puesto_id', 'numero_fijo','numero_celular',
    'direccion','dui','correo_electronico','fecha_de_nacimiento'];
    
    public function puesto()
    {
        return $this->belongsTo(Puesto::class);
    }



}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use App\Empleado;
use App\Http\Requests\CreateEmpleadoRequest;
use App\Http\Requests\EditEmpleadoRequest;
use App\Puesto;
use Illuminate\Http\Request;

class EmpleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $empleados = Empleado::join("puestos","puestos.id","=","empleados.puesto_id" )
            ->select("empleados.id","empleados.codigo","empleados.nombre","empleados.apellido","puestos.name as puesto")
            ->get();
        

        return view('empleados.index',['empleados'=>$empleados]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $puestos= \App\Puesto::all();

        return view ('empleados.create', ['puestos'=>$puestos]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEmpleadoRequest $request)
    {
        /*Empleado::create([
            'nombre'=>$request->nombre,
            'apellido'=>$request->apellido,
            'puesto_id'=>$request->puesto_id,
            'numero_fijo'=>$request->numero_fijo,
            'numero_celular'=>$request->numero_celular,
            'direccion'=>$request->direccion,
            'dui'=>$request->dui,
            'correo_electronico'=>$request->correo_electronico,
            'fecha_de_nacimiento'=>$request->fecha_de_nacimiento,
        ]);*/
        Empleado::create($request->validated());
   
        return redirect()->route('empleados.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function show(Empleado $empleado)
    {
        $puestos= \App\Puesto::all();
        return view('empleados.show',['puestos'=>$puestos], ['empleado'=>$empleado]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function edit(Empleado $empleado)
    {
        $puestos= \App\Puesto::all();
        return view ('empleados.edit', ['puestos'=>$puestos], ['empleado'=>$empleado]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function update(EditEmpleadoRequest $request, Empleado $empleado)
    {
       /* $request->validate([
            'nombre'=>'required',
            'apellido'=>'required',
            'puesto_id'=>'required',
            'numero_fijo'=>'required',
            'numero_celular'=>'required',
            'direccion'=>'required',
            'dui'=>'required',
            'correo_electronico'=>'required',
            'fecha_de_nacimiento'=>'required',
        ]);*/

        $empleado->update($request->validated());
  
        return redirect()->route('empleados.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function destroy(Empleado $empleado)
    {
        $empleado->delete();
  
        return redirect()->route('empleados.index')->with('eliminar','okey');
    }
}

resources/views/empleados/create.blade.php
@extends('layouts.app')
@section('title', 'Crear Nuevo Empleados')
@section('content')
<div class="grid-container">
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>¡Alerta!</strong> Se tienen un problema con los siguientes campos:
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="grid-item">
        <form action="{{ route('empleados.store') }}" method="POST">
            @csrf
                <h2>Agregar un nuevo empleado</h2>
            <div class="form-group">
                <label class="form-label">Codigo</label>
                <input type="text" class="form-control" name="codigo" id="codigo" placeholder="Ingrese su codigo" value="{{old('codigo')}}">
            </div>
            <div class="form-group">
                <label class="form-label">Nombre</label>
                <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Ingrese su nombre" value="{{old('nombre')}}">
            </div>
            <div class="form-group">
                <label class="form-label">Apellido</label>
                <input type="text" class="form-control" name="apellido" id="apellido" placeholder="Ingrese su Apellido" value="{{old('apellido')}}">
            </div>
        
            <div class="form-group">
                <label class="form-label">Puesto de trabajo</label>
                    <select class="form-control selectorWapis" id="puesto" name="puesto_id">
                        <option value="" selected disabled hidden>Seleccione el puesto *</option>
                        @foreach ($puestos as $puesto)
                            @if (old('puesto')==$puesto->id)                                     
                                <option  value="{{$puesto->id}}" selected>{{ $puesto->name }}</option>
                            @else
                                <option  value="{{$puesto->id}}">{{ $puesto->name }}</option>
                            @endif                                
                        @endforeach
                    </select>
            </div>
            <div class="form-group">
                <label class="form-label">Telefono</label>
                <input type="Number" class="form-control"name="numero_fijo" id="numero_fijo" placeholder="22222222" value="{{old('numero_fijo')}}">
            </div>
            <div class="form-group">
                <label class="form-label">Telefono Celular</label>
                <input type="Number" class="form-control" name="numero_celular" id="numero_celular" placeholder="77777777" value="{{old('numero_celular')}}">
            </div>
            <div class="form-group">
                <label class="form-label">Direccion</label>
                <input type="text" class="form-control" name="direccion" id="direccion" placeholder="Calle San Antonio Colonia San Jacinto" value="{{old('direccion')}}">
            </div>
            <div class="form-group">
                <label class="form-label">DUI</label>
                <input type="text" class="form-control" maxlength="10" name="dui" id="dui" placeholder="012345678-9" value="{{old('dui')}}">
            </div>
            <div class="form-group">
                <label class="form-label">Email address</label>
                <input type="email" class="form-control" name="correo_electronico" id="correo_electronico" placeholder="ejemplo@example.com" value="{{old('correo_electronico')}}">
            </div>
            <div class="form-group">
                <label class="form-label">Fecha de Nacimiento</label>
                <input type="Date" class="form-control" name="fecha_de_nacimiento" id="fecha_de_nacimiento" placeholder="DD/MM/AAAA" value="{{old('fecha_de_nacimiento')}}">
            </div>
            <div class=" row grid-item buttom-center">
                <button type="submit" class="btn btn-primary botton-general">Guardar</button>          
                <a type="submit" class="btn btn-danger botton-general" href="{{route('empleados.index')}}">Cancelar</a>  
            </div>
        </form>
    </div>

</div>

            

           

@endsection

resources/views/empleados/edit.blade.php
@extends('layouts.app')
@section('title', 'Editar Empleado')
@section('content')
<div class="grid-container">
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>¡Alerta!</strong> Se tienen un problema con los siguientes campos:
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            
        </div>
    @endif
    <div class="grid-item">
        <form action="{{route('empleados.update', $empleado->id)}}" method="POST">
            @csrf
            @method('PUT') 
            <h2>Modificando datos de un empleado</h2>

            <div class="form-group">
                <label class="form-label">Codigo</label>
                <input type="text" class="form-control" name="codigo" id="codigo" placeholder="Ingrese su nombre" 
                value="{{$empleado->codigo}}">
            </div>

            <div class="form-group">
                <label class="form-label">Nombre</label>
                <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Ingrese su nombre" 
                value="{{$empleado->nombre}}">
            </div>
            <div class="form-group">
                <label class="form-label">Apellido</label>
                <input type="text" class="form-control" name="apellido" id="apellido" placeholder="Ingrese su Apellido" 
                value="{{$empleado->apellido}}">
            </div>
        
            <div class="form-group">
                <label class="form-label">Puesto de trabajo</label>
                    <select class="form-control selectorWapis" id="puesto" name="puesto_id">
                        <option value="" selected disabled hidden>Seleccione el puesto *</option>
                        @foreach ($puestos as $puesto)
                            @if ($empleado->puesto_id==$puesto->id)                                     
                                <option  value="{{$puesto->id}}" selected>{{ $puesto->name }}</option>
                            @else
                                <option  value="{{$puesto->id}}">{{ $puesto->name }}</option>
                            @endif                                
                        @endforeach
                    </select>
            </div>
            <div class="form-group">
                <label class="form-label">Telefono</label>
                <input type="Number" class="form-control"name="numero_fijo" id="numero_fijo" placeholder="22222222" 
                value="{{$empleado->numero_fijo}}">
            </div>

            <div class="form-group">
                <label class="form-label">Telefono Celular</label>
                <input type="Number" class="form-control" name="numero_celular" id="numero_celular" placeholder="77777777" 
                value="{{$empleado->numero_celular}}">
            </div>

            <div class="form-group">
                <label class="form-label">Direccion</label>
                <input type="text" class="form-control" name="direccion" id="direccion" placeholder="Calle San Antonio Colonia San Jacinto" 
                value="{{$empleado->direccion}}">
            </div>
            <div class="form-group">
                <label class="form-label">DUI</label>
                <input type="text" class="form-control" maxlength="10" name="dui" id="dui" placeholder="012345678-9" 
                value="{{$empleado->dui}}">
            </div>

            <div class="form-group">
                <label class="form-label">Email address</label>
                <input type="email" class="form-control" name="correo_electronico" id="correo_electronico" placeholder="ejemplo@example.com" 
                value="{{$empleado->correo_electronico}}">
            </div>

            <div class="form-group">
                <label class="form-label">Fecha de Nacimiento</label>
                <input type="Date" class="form-control" name="fecha_de_nacimiento" id="fecha_de_nacimiento" placeholder="DD/MM/AAAA" 
                value="{{$empleado->fecha_de_nacimiento}}">
            </div>
            
            <div class=" row grid-item buttom-center">
                <button type="submit" class="btn btn-primary botton-general">Modificar</button>          
                <a class="btn btn-danger botton-general" href="{{route('empleados.index')}}">Cancelar</a>     
            </div>
             
        </form>
    </div>
</div>

@endsection

resources/views/empleados/index.blade.php
@extends('layouts.app')
@section('title', 'Empleados')
@section('content')
<div class="grid-container">

    <div class="grid-titulo-inicial">
        <h3>Listado de Empleados</h3>
    </div>

    <div class="grid-buttom-index">
        <a class="btn btn-primary botton-general" href="{{ route('empleados.create') }}"> Agregar un Nuevo Empleado</a>
        <a  type="submit"  class="btn btn-primary botton-general" href="{{ route('asistencias.create') }}">Asistencia</a>
    </div>

    <div class="grid-table">  
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>¡Alerta!</strong> Se tienen un problema con los siguientes campos:
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @section('CSS')
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
            <link rel="stylesheet" href="https://cdn.datatables.net/1.12.0/css/dataTables.bootstrap4.min.css">
            @endsection

            <table id="empleado" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Codigo</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Puesto</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($empleados as $empleado)
                        <tr>
                            <td>{{$empleado->codigo}}</td>
                            <td>{{$empleado->nombre}}</td>
                            <td>{{$empleado->apellido}}</td>
                            <td>{{$empleado->puesto}}</td>
                            <td>
                                <div class="row">
                                    <a  type="submit"  class="btn btn-sm btn-primary botton-general" href="{{ route('empleados.edit',$empleado->id) }}">Editar</a>
                                    <a  type="submit"  class="btn btn-sm btn-secondary botton-general"  href="{{ route('empleados.show',$empleado->id) }}">Mostrar</a>
                                    <form action="{{route('empleados.destroy', $empleado)}}" id="test"  method="POST" >
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger botton-general" onclick="return confirm('¿Quiere eliminar este empleado?')">Eliminar</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            @section('js')

                <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
                <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
                <script src="https://cdn.datatables.net/1.12.0/js/dataTables.bootstrap4.min.js"></script>    

                <script>
                    $(document).ready(function () {
                    $('#empleado').DataTable();
                    });
                </script>
            @endsection            
    </div>  
</div>
@endsection

resources/views/empleados/show.blade.php
@extends('layouts.app')
@section('title', 'Datos del Empleado')
@section('content')
<div class="grid-container">

    <div class="grid-item">

        <h2>Datos del empleado</h2>
        
        <form action="{{route('empleados.show', $empleado->id)}}" method="POST">
            @csrf
            @method('PUT') 

            <a class="btn btn-success" href="{{route('empleados.index')}}">Regresar</a>
            
            <label class="form-label">Codigo</label>
            <label>{{$empleado->codigo}}</label>

            <label class="form-label">Nombre</label>
            <label>{{$empleado->nombre}}</label>

            <label class="form-label">Apellido</label>
            <label>{{$empleado->apellido}}</label>

                

            <div class="form-group">
                <label for="exampleFormControlInput1" class="form-label">Puesto de trabajo</label>
                    <select disabled class="form-control selectorWapis" id="puesto" name="puesto_id">
                        <option value="{{$empleado->puesto_id}}" selected disabled hidden>Seleccione el puesto *</option>
                        @foreach ($puestos as $puesto)
                            @if ($empleado->puesto_id==$puesto->id)                                     
                                <option  value="{{$puesto->id}}" selected>{{ $puesto->name }}</option>
                            @else
                                <option  value="{{$puesto->id}}">{{ $puesto->name }}</option>
                            @endif                                
                        @endforeach
                    </select>
            </div>
            <div class="form-group">
                <label class="form-label">Telefono</label>
                <input disabled type="Number" class="form-control"name="numero_fijo" id="numero_fijo" placeholder="22222222" 
                value="{{$empleado->numero_fijo}}">
            </div>
            <div class="form-group">
                <label class="form-label">Telefono Celular</label>
                <input  disabled type="Number" class="form-control" name="numero_celular" id="numero_celular" placeholder="77777777" 
                value="{{$empleado->numero_celular}}">
            </div>
            <div class="form-group">
                <label class="form-label">Direccion</label>
                <input disabled type="text" class="form-control" name="direccion" id="direccion" placeholder="Calle San Antonio Colonia San Jacinto" 
                value="{{$empleado->direccion}}">
            </div>
            <div class="form-group">
                <label class="form-label">DUI</label>
                <input disabled type="text" class="form-control" maxlength="10" name="dui" id="dui" placeholder="012345678-9" 
                value="{{$empleado->dui}}">
            </div>
            <div class="form-group">
                <label class="form-label">Email address</label>
                <input disabled type="email" class="form-control" name="correo_electronico" id="correo_electronico" placeholder="ejemplo@example.com" 
                value="{{$empleado->correo_electronico}}">
            </div>
            <div class="form-group">
                <label class="form-label">Fecha de Nacimiento</label>
                <input disabled type="Date" class="form-control" name="fecha_de_nacimiento" id="fecha_de_nacimiento" placeholder="DD/MM/AAAA" 
                value="{{$empleado->fecha_de_nacimiento}}">
            </div>         
              
        </form>
    </div>
</div> 

@endsection