routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('menu1', function(){
	return view('menu1.index');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('empleados','EmpleadoController');
Route::resource('puestos','PuestoController');
Route::resource('asistencias','AsistenciaController');

app/Puesto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Puesto extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/PuestoController.php
<?php

namespace App\Http\Controllers;

use App\Puesto;
use Illuminate\Http\Request;

class PuestoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $puestos = Puesto::all();

        return view ('puestos.index',['puestos'=>$puestos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Puestos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Puesto::create([
            'name'=>$request->name,
        ]);
        return redirect()->route('puestos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Puesto  $puesto
     * @return \Illuminate\Http\Response
     */
    public function show(Puesto $puesto)
    {
        return view('puestos.show', ['puesto'=>$puesto]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Puesto  $puesto
     * @return \Illuminate\Http\Response
     */
    public function edit(Puesto $puesto)
    {
        return view('puestos.edit', ['puesto'=>$puesto]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Puesto  $puesto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Puesto $puesto)
    {
        $puesto->update([
            'name' => $request->name,
        ]);
        return redirect()->route('puestos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Puesto  $puesto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Puesto $puesto)
    {
        $puesto->delete();
  
        return redirect()->route('puestos.index');
    }
}

resources/views/puestos/create.blade.php
@extends('layouts.app')
@section('title', 'Crear Nuevo Puesto')
@section('content')
<div class="content-header">
  <div class="container-fluid">
        <div class="container">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>¡Alerta!</strong> Se tienen un problema con los siguientes campos:
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('puestos.store') }}" method="POST">
                @csrf
                <div class="pull-right">
                    <h2>Agregar un nuevo puesto</h2>
                </div>
                <div class="form-group">
                    <label class="form-label">Nombre</label>
                    <input type="text" class="form-control" name="name" id="name" placeholder="Ingrese su nombre del puesto" value="{{old('name')}}">
                </div>
            
                <button type="submit" class="btn btn-primary">Guardar</button>          
                <a type="submit" class="btn btn-danger" href="{{route('puestos.index')}}">Cancelar</a>  
            </form>
        </div>
  </div>
</div>
@endsection

resources/views/puestos/edit.blade.php
@extends('layouts.app')
@section('title', 'Editar Puesto')
@section('content')
<div class="grid-container">
    
    <div class="grid-item">
        <h3>Modificando un puesto</h3>
    </div>

    <div class="grid-item">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>¡Alerta!</strong> Se tienen un problema con los siguientes campos:
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        <form action="{{route('puestos.update', $puesto->id)}}" method="POST">
            @csrf
            @method('PUT') 
                    <div class="form-group">
                        <label class="form-label">Nombre</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Ingrese el nombre del puesto" 
                        value="{{$puesto->name}}">
                    </div>
            <div class=" row grid-item buttom-center">
                <button type="submit" class="btn btn-primary botton-general">Modificar</button>          
                <a class="btn btn-danger botton-general" href="{{route('puestos.index')}}">Cancelar</a>      
            </div>          
        </form>
    </div>
</div>
@endsection

resources/views/puestos/index.blade.php
@extends('layouts.app')
@section('title', 'Puestos')
@section('content')
<div class="grid-container">
    
    <div class="grid-titulo-inicial">
        <h3>Listado de Puestos</h3>
    </div>
    
    <div class="grid-buttom-index">
        <a class="btn btn-primary botton-general" href="{{ route('puestos.create') }}"> Agregar un Nuevo Puesto</a>
    </div>

    <div class="grid-table">
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>¡Alerta!</strong> Se tienen un problema con los siguientes campos:
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @section('CSS')
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.12.0/css/dataTables.bootstrap4.min.css">
        @endsection

        <table id="puestos" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Nombre</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ($puestos as $puesto)
                    <tr>
                        <td>{{$puesto->id}}</td>
                        <td>{{$puesto->name}}</td>
                        <td>
                            <div class="row">
                                <a  type="submit"  class="btn btn-sm btn-primary botton-general" href="{{ route('puestos.edit',$puesto->id) }}">Editar</a>
                                <a  type="submit"  class="btn btn-sm btn-secondary botton-general"  href="{{ route('puestos.show',$puesto->id) }}">Mostrar</a>
                                <form action="{{route('puestos.destroy', $puesto)}}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-sm btn-danger botton-general" onclick="return confirm('¿Quiere eliminar este puesto?')">Eliminar</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

        @section('js')
            <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
            <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
            <script src="https://cdn.datatables.net/1.12.0/js/dataTables.bootstrap4.min.js"></script>

            <script>
                $(document).ready(function () {
                $('#puestos').DataTable();
                });
            </script>
        @endsection            
    </div>
</div>
@endsection

resources/views/puestos/show.blade.php
@extends('layouts.app')
@section('title', 'Datos del Puesto')
@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="container">
            <div class="pull-right">
                <h2>Datos del puesto</h2>
            </div>
            <form action="{{route('puestos.show', $puesto->id)}}" method="POST">
                @csrf
                @method('PUT') 
            
                <div class="form-group">
                    <label class="form-label">Nombre</label>
                    <input disabled type="text" class="form-control" name="name" id="name" placeholder="Ingrese su nombre" 
                    value="{{$puesto->name}}">
                </div>        
                <a class="btn btn-success" href="{{route('puestos.index')}}">Regresar</a>  
            </form>
    </div> 
  </div>
</div>
@endsection