routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('menu1', function(){
	return view('menu1.index');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('empleados','EmpleadoController');
Route::resource('puestos','PuestoController');
Route::resource('asistencias','AsistenciaController');

app/asistencia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class asistencia extends Model
{
    protected $fillable = ['codigo','fecha_laboral','hora_laboral'];
 
    public function puesto()
    {
        return $this->belongsTo(Empleado::class);
    }
}

app/Http/Controllers/AsistenciaController.php
<?php

namespace App\Http\Controllers;

use App\asistencia;
use App\Empleado;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Symfony\Component\Console\Input\Input;

class AsistenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    } 

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('asistencias.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

         $codigo = $request->get('codigo');
         $empleado = Empleado::where('codigo','=',"$codigo")->count();

         if (empty($empleado)){
            return 'Codigo no encontrado';
         }

         else{
            $date = Carbon::now();
            $fecha_actual =$date->toDateString();
            $hora_actual =$date->toTimeString();
   
            asistencia::create([
               'codigo'=>$request->codigo,
               'fecha_laboral'=>$fecha_actual,
               'hora_laboral'=>$hora_actual,
           ]);
           
           return back()->with(['mensaje' => 'Asistencia con exito']);
         }
         

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/asistencias/create.blade.php
@extends('layouts.app')
@section('title', 'Asistencia')
@section('content')
<div class="grid-container">

    <div class="grid-item">
        <h3>Asistencia</h3>
    </div>

    <div class="grid-item">
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong>Se tienen un problema con los siguientes campos:<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('asistencias.store') }}" method="POST">
                @csrf
            <div class="form-group">
                <label class="form-label">Codigo</label>
                <input type="text" class="form-control" name="codigo" id="codigo" placeholder="Ingrese su codigo">
            </div>
            <label for="">{{$mensaje ?? ''}}</label>

            <div class=" row grid-item buttom-center">
                <button type="submit" class="btn btn-primary botton-general">Guardar</button>          
                <a type="submit" class="btn btn-danger botton-general" href="{{route('empleados.index')}}">Cancelar</a>  
            </div> 
                
        </form>
        
        @section('scripts')
            <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        
        @endsection
    </div>
</div>
@endsection

resources/views/asistencias/index.blade.php
@extends('layouts.app')
@section('title', 'Asistencia')
@section('content')
<div class="content-header">
            <div class="pull-right">
                <h2>Asistencia</h2>
            </div>
    
  <div class="container-fluid">
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong>Se tienen un problema con los siguientes campos:<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @section('CSS')
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.12.0/css/dataTables.bootstrap4.min.css">
        @endsection

       

        @section('js')
            <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
            <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
            <script src="https://cdn.datatables.net/1.12.0/js/dataTables.bootstrap4.min.js"></script>

            <script>
                $(document).ready(function () {
                $('#empleado').DataTable();
                });
            </script>
        @endsection            
  </div>
</div>
@endsection